name: BuildPolicyInitiatives 🏗️  ~ $(Date:yyyy-MM-dd HH-mm) UTC


pr: none
trigger: none


resources:
  repositories:
  - repository: libraries
    type      : git
    name      : Global/glb-libraries
    ref       : refs/heads/main

  - repository: initiatives
    type      : git
    name      : Global/glb-initiatives
    ref       : refs/heads/main


parameters:
- name       : env
  displayName: Please select your environment
  default    : ten
  values     :
  - ten


variables:
- name : POLICY_ENVIRONMENT
  value: ${{ parameters.env }}

- name : POLICY_TENANT
  value: ${{ parameters.env }}

- template: /params/${{ parameters.env }}/config.yml


stages:
- template: /pipelines/01_stage/pol_release.yml@libraries
  parameters:
    environment: ${{ parameters.env }}
    mgmtGroupName:
    - name    : global
      shortEnv: ten
      repositories:
      - nameLong : glb-initiatives
        nameShort: initiatives
